#!/bin/sh
prompt=$(date +"%a %d. %b %R")
num=$(wmctrl -l | awk '{$1="";$2="";$3="";gsub(/  /,"", $0);printf("%d - %s\n",NR,$0)}' | dmenu -fn "Verdana" -nb "#7F7F7F" -nf "#FFFFFF" -i -p "$prompt" -l 30 | cut -d"-" -f1)
[ -z "$num" ] || wmctrl -l | awk -v n="$num" 'NR==n { print $1 }' | xargs wmctrl -i -a
